### ISSUE TITLE
Change API to Open Library Books

### ISSUE THREAD

**Issue by bcye** [bcye/whathaveiread#13]
Google Books requires API users to implement tons of watermarks, that don't really work with this application.

Solution:
Change the API to Open Library Books.
For this, the JSON must be parsed differently, due to another structure (obviously)

Task:

Change (and refactor) the scanning/downloading/parsing code so it works with the Open Library Books API.

Resources about the API can be found [here.](https://openlibrary.org/dev/docs/api/books)
We need to use the jscmd=details parameter, to get the description of the book.
We would query the book in ISBN:13

[Sample request](https://openlibrary.org/api/books?bibkeys=ISBN:9780439708180&format=json&jscmd=details)

**Comment by damien-rivet** [comment]
Hi,

I'd love to work on migrating toward the `Open Library` API.

**Edit:** PR is now opened.
