### ISSUE TITLE
Create App Screenshots for version release 2.0 

### ISSUE THREAD

**Issue by bcye** [bcye/whathaveiread#17]
Thanks to the many contributions, version 2.0 will be soon released.
Create App Screenshots and a short movie to showcase the app in the Apple App Store.

> 1242 x 2208 pixels for portrait
> 5.5-Inch Retina Display (iPhone 6s Plus, iPhone 7 Plus, iPhone 8 Plus)

[This website describes the specifications needed for the video.](https://help.apple.com/app-store-connect/#/dev4e413fcb8)

**Comment by bcye** [comment]
Refer to these pull requests for changes in this version: #15 #14 #12 #11 #10 #9 #8 #5

**Comment by dicky513** [comment]
tes
