### ISSUE TITLE
Integration with Siri Shortcuts

### ISSUE THREAD

**Issue by MatejMecka** [bcye/whathaveiread#2]
It would be nice if i can just tell siri to add a book to my what have i read list and fill out some of the details for me.

**Comment by bcye** [comment]
This could be a good Hacktoberfest issue.

In [WWDC Session](https://developer.apple.com/videos/play/wwdc2018/211/) it is explained, how to integrate an app with Siri Shortcuts. A possible could be to add a new book.

**Comment by pankova** [comment]
Hi! May i help with Shortcuts?

**Comment by bcye** [comment]
@pankova Of course! Do you have questions about the issue?

**Comment by bcye** [comment]
@pankova Do you still want to help? Else I would start development.

**Comment by shashikanth-a** [comment]
Can i work on this issue ?

**Comment by bcye** [comment]
Seems like @pankova has no interest anymore.
It would be awesome if you would be able to help @shashikanth-a on these 2 issues.
Tell me if something is unclear.

**Comment by shashikanth-a** [comment]
Would you provide google books api key or shall i create one by changing
the bundle id ?

**Comment by bcye** [comment]
@shashikanth-a You can create your own or just don't use the functionality, while programming.

**Comment by pankova** [comment]
@bcye hey! I didn't say, i'm not interested in it(
