### ISSUE TITLE
Over-complete API data model

### ISSUE THREAD

**Issue by raysarebest** [bcye/whathaveiread#27]
The model in `OpenLibraryBook.swift` contains *a lot* of data. However, much of it is non-optional, and the app itself doesn't use most of it. Worse yet, since most (if not, all) of it is non-optional, that means that decoding will fail for a book that has lots of valid data, but not for every key. I propose that we mark only the properties that the app uses as non-optional

Of course, this means we'll need to figure out what to do about the other data. There are 3 paths I see with this:

- Just delete all the references to it and only keep the data we need
- Keep all the properties that exist, but mark all but the ones we use as optional and decode them only if present
- Make properties for just the data we need, and put the rest into a dictionary property
    - Maybe allow `@dynamicMemberLookup` for access to that dictionary?

**Comment by bcye** [comment]
I would go for option 2, this makes it easier to access the properties in future versions, where we might want to access them

**Comment by raysarebest** [comment]
Potentially related issue: Right now, we're passing the `details` parameter to the OpenLibrary API, but [the documentation](https://openlibrary.org/dev/docs/api/books) specifically says that this isn't recommended, and one should probably be passing `data` instead, since that's a more stable format. The keys for that are far better documented than what we're doing right now. The downside is that it *doesn't* include a description of the book, which I see we're using when it's available. What're your thoughts on switching to this version of the API?

**Comment by bcye** [comment]
We need the description, that's the whole point of the scanner.
