### ISSUE TITLE
The user should be able to share books

### ISSUE THREAD

**Issue by bcye** [bcye/whathaveiread#3]
The user should be able to share books they have read with friends.

You could provide a share button in the book detail view controller that will share the title and the description of the book to a service. (via the share menu)

**Comment by pankova** [comment]
Hi! May i help with sharing?

**Comment by bcye** [comment]
@pankova Of course! Do you have questions about the issue?

**Comment by shashikanth-a** [comment]
Can i work on this issue ?

**Comment by bcye** [comment]
#5 Thanks again! @shashikanth-a

**Comment by pankova** [comment]
@bcye hey! I didn't say, i'm not interested in it(

**Comment by bcye** [comment]
Sorry man. Were 2 days and so I assumed it...

**Comment by pankova** [comment]
Ok) Sorry to
