### ISSUE TITLE
.csv backups and CloudKit functionality

### ISSUE THREAD

**Issue by bcye** [bcye/whathaveiread#35]
**Is your feature request related to a problem? Please describe.**
At the moment, when one moves to a new phone or reinstalls the app, all the data is gone.

**Describe the solution you'd like**
What about letting users export and information of the book into a .csv spreadsheet.

**Describe alternatives you've considered**
We could also integrate the app with CloudKit, which would have the other benefit of users having the same data on their phones and iPads

I'm not sure which of the options to choose and would go for both, (backups for people who want that and CloudKit)

CloudKit has also a financial perspective, but 100MB for free per user which should be more than enough, plus that the app now costs something, so that can be paid by that

**Comment by raysarebest** [comment]
Tbh I'd go both CloudKit and an export/import function

**Comment by bcye** [comment]
just what I mentioned 😆

**Comment by bcye** [comment]
I would work on it for 2.1

**Comment by bcye** [comment]
I started working on this in dev/cloudkit. I think the best bet is to go with a framework: https://github.com/Sorix/CloudCore
