### ISSUE TITLE
Add an iMessage app

### ISSUE THREAD

**Issue by bcye** [bcye/whathaveiread#6]
I had the idea of adding an iMessage app to the app. The interface could be similar to the main view controller.

If someone wants to do this for hacktoberfest, grab it. Else I will probably start working on it.

**Comment by aitemr** [comment]
Hi, @bcye 

I want to implement this feature!

**Comment by bcye** [comment]
@aitemr Sure, would be awesome! Please do it in a NEW branch in your fork, else it’s a bit hard to add your fork as a remote

**Comment by bcye** [comment]
@aitemr Do you still (want to) work on this?

**Comment by bcye** [comment]
https://developer.apple.com/videos/play/wwdc2016/204/
