### ISSUE TITLE
Localize the app to your language

### ISSUE THREAD

**Issue by bcye** [bcye/whathaveiread#7]
<img width="1680" alt="screen shot 2018-10-11 at 3 23 54 pm" src="https://user-images.githubusercontent.com/29666239/46837342-d692b880-cd69-11e8-9003-43943e45eeb2.png">
As seen on the picture, for adding a localization, the project must be selected and not the target.
You can then import the Localization and open a pull request.

For more information on iOS localization (and if you need help), ask me or refer [to this talk at WWDC on the new Xcode localization workflow]( https://developer.apple.com/videos/play/wwdc2018/404/).

**Comment by pankova** [comment]
Hi! May i help? I can add Russian translate

**Comment by bcye** [comment]
@pankova Sure! You're always welcome to help.

**Comment by klymenkoo** [comment]
I can add Ukrainian localization if you don't mind @bcye

**Comment by damien-rivet** [comment]
Hi,

I'll gladly contribute to the French strings 😄
